### PR TITLE
Update restore intro.md

### PR DESCRIPTION
**Pull request by kapitainsky**
to bring it in line with the latest `rustic restore --help`

### CODE REVIEW

**Comment by kapitainsky** [comment]
> Tried to fix it with a format action, but need to work more on it. ;-) So for now, you need to format yourself.

Thx for trying. I do not mind to format things myself but I have no clue what the problem is.

Do you have any guidelines for contributors?

**Comment by kapitainsky** [comment]
> > Tried to fix it with a format action, but need to work more on it. ;-) So for now, you need to format yourself.
> 
> Thx for trying. I do not mind to format things myself but I have no clue what the problem is.
> 
> Do you have any guidelines for contributors?

Thx for that. I have tried. Nothing shows any errors. I have no clue how I am supposed to figure out which formatting is not perfect.

My edits were quite simple so I suspect that even your original file would not pass your checks. I will try next year to come back to it.

**Review by aawsome — APPROVED** [review]
LGTM!

**Comment by kapitainsky** [comment]
OK - I am getting up to speed with this repos ways:)

**Pull request merged**
